### ISSUE TITLE
[Phoenix 1.3] GraphQL on the Server

### ISSUE THREAD

**Issue by zimt28** [absinthe-graphql/absinthe_phoenix#2]
Just opening again as a place to track the progress of calling GraphQL on the server via Absinthe.

Some context:

- https://github.com/absinthe-graphql/absinthe/issues/281
- https://elixirforum.com/t/phoenix-graphql-tutorial-with-absinthe-add-crud-using-mutations/2729/11
- https://youtu.be/IMUpYOc9z3c?t=24m58s

**Comment by benwilson512** [comment]
This is an idea we want to continue exploring at some point but it doesn't have a spot on the current road map.
