### ISSUE TITLE
isDeepEqual is not defined

### ISSUE THREAD

**Issue by dvanderbeek** [absinthe-graphql/absinthe_phoenix#28]
Hello! I'm trying to set up a simple example app using absinthe_phoenix, but I can't get the subscriptions to work. When I run a subscription query in GraphiQL with no WS URL configured, I get this (as expected): "Subscriptions cannot be run over HTTP. Please configure a websocket connection"

When I set the WS URL to `ws://localhost:4000/graphiql` or `ws://localhost:4000/socket` (or use the simple GraphiQL interface) and run my query, I do not see anything in the network panel of my browser and the only thing that shows up in the query results pane is `isDeepEqual is not defined`. I'm sure there is something simple that I'm missing, but I followed the guides and can't get it to work. Any help would be appreciated!

**Comment by benwilson512** [comment]
Hey @dvanderbeek. We've seen this issue too, but since `Absinthe.Plug` is where GraphiQL is hooked in we made the issue over there: https://github.com/absinthe-graphql/absinthe_plug/issues/133

**Comment by dvanderbeek** [comment]
@benwilson512 Thanks. Just to document my solution, I just changed my mix.exs entry for absinthe_plug to `{:absinthe_plug, git: "https://github.com/absinthe-graphql/absinthe_plug.git", ref: "c2bcef26360f9b31f122e25ac0cbfdd1b76455f7", override: true},` for now and it works
