### ISSUE TITLE
Phoenix's `action_fallback` is not respected

### ISSUE THREAD

**Issue by brainlid** [absinthe-graphql/absinthe_phoenix#34]
Using the master branch of `absinthe_phoenix`'s Controller to support REST interface calls to a GraphQL backend, the standard Phoenix.Controller `action_fallback` feature is not supported.

```elixir
defmodule MyProject.AwesomeController do
  use Phoenix.Controller
  use Absinthe.Phoenix.Controller, schema: Graph.Schema

  action_fallback Api.Web.JsonGraphFallbackResponse

  # ...
end
```

It doesn't error, but the call function in the specified fallback module never executes. 

Ideally the `action_fallback` would be respected so I can, in one place, handle unexpected GraphQL errors.

Love the library! Such an awesome time saver!

**Comment by zimt28** [comment]
Can you share what you‘ve tried or expect?

**Comment by brainlid** [comment]
Thank you for the follow-up prompt. After revisiting the code, I realized the issue was on my side from a different problem. `action_fallback` is working. :)
