### ISSUE TITLE
:id type case

### ISSUE THREAD

**Issue by G3z** [absinthe-graphql/absinthe_phoenix#4]
Hello,
I'm not sure this is even an issue but I noticed that `:id` types are passed as typed by the query (I'm using uuids) to trigger function.
I noticed Ecto always returns a lowercase version of the uuid
no big deal but I had trouble finding the issue because in queries it's transparent
this is how i fixed the problem

     topic fn args ->
        String.downcase(args.group_id)
      end

I don't know if you want to mention this in the readme or fix it automagically

**Comment by benwilson512** [comment]
Hey there. The build in ID type doesn't do any transformation of values at all other than just calling `to_string` on it. I can understand that in your situation it makes sense to use String.downcase, but I guess I'm not really sure that this is an issue with Absinthe.

After all there's no intrinsic reason why some database couldn't used mixed case identifiers, in which case the `String.downcase` would actually cause bugs.
