### ISSUE TITLE
1.4.0-beta.1 release is missing socket.ex file

### ISSUE THREAD

**Issue by astery** [absinthe-graphql/absinthe_phoenix#5]
It's missing in hex package and in github release tar.

**Comment by benwilson512** [comment]
Ah, this is an unfortunate situation where the readme on github has been updated, but the code has not. If you check out the readme on the actual release you'll see that there's no mention of socket https://github.com/absinthe-graphql/absinthe_phoenix/tree/1.4.0-beta.1 as it was called Channel at the time.

**Comment by astery** [comment]
Got it, thanks!
