### ISSUE TITLE
Catchall `handle_info` in channel

### ISSUE THREAD

**Issue by bernardd** [absinthe-graphql/absinthe_phoenix#50]
Would it be reasonable to add a catchall `handle_info` function to `Absinthe.Phoenix.Channel`? ie:

```elixir
def handle_info(_, socket), do: {:noreply, socket}
```

The reason I ask is that we have a "waiter" type module which waits on a specific message with a timeout. BEAM being what it is, of course, it's nigh on impossible to completely guarantee that that message won't arrive after the timeout. In the current form, if this happens the channel will crash with a function clause error. A catchall would solve that, but I understand if it seems maybe overly broad. If you don't like that idea, would it be reasonable to rejig it so that the user can specify their own handle_info overrides (just like is currently done for `Phoenix.Channel`)?

**Comment by benwilson512** [comment]
Included in latest release!

**Comment by maartenvanvliet** [comment]
This can be closed :)
