### ISSUE TITLE
Superviser example code doesn't work with latest Exlir

### ISSUE THREAD

**Issue by xtagon** [absinthe-graphql/absinthe_phoenix#51]
Hi, 

The README currently contains the instructions:

In your application supervisor add a line AFTER your existing endpoint supervision
line:

```elixir
[
  # other children ...
  supervisor(MyAppWeb.Endpoint, []), # this line should already exist
  supervisor(Absinthe.Subscription, [MyAppWeb.Endpoint]), # add this line
  # other children ...
]
```

Where `MyAppWeb.Endpoint` is the name of your application's phoenix endpoint.

I had to modify this slightly to work with Elixir 1.7:

```elixir
[
  # other children ...
  MyAppWeb.Endpoint, # this line should already exist
  # add these lines:
  %{
    id: Absinthe.Subscription,
    start: {Absinthe.Subscription, :start_link, [MyApp.Endpoint]},
    type: :supervisor
  }
  # other children ...
]
```

This got it to work for me-- is this the correct way to do it now, and should the docs be updated to reflect this?

Thanks 👍

**Comment by hauleth** [comment]
You probably can use `{Absinthe.Subscription, [MyApp.Endpoint]}` as well, as default `mod.child_spec/1` will work in the same way as you have presented.

**Comment by xtagon** [comment]
@hauleth Thank you that sounds right! I was getting confused because I've been locked to an older Elixir version for a while. Closing because it's not an issue with Absinthe-Phoenix then.
