### ISSUE TITLE
Absinthe subscriptions OOM-ing processes

### ISSUE THREAD

**Issue by michaeljguarino** [absinthe-graphql/absinthe_phoenix#61]
I've been working on a personal project as a way to experiment with graphql on elixir, and came across some odd behavior.  If I initiate maybe 20-30 or so subscribe/resubscribes, it will kill the node due to an OOM error.  I've used vanilla phoenix pubsub extensively for almost 3 years now, and never had any similar issue (although you do sometimes need to manually gc them), and just to confirm, I disabled graphql subscriptions and left the few channels being used for presence and similar use cases up, and had no memory usage issues.

My hesitant guess is something about my graphql schema is complex enough to require a massive footprint, but it still seems very suspicious.

Here's some specs:

- running on GKE with .5 vcpu/2Gi per container
- steady state with maybe 2 gql subscriptions takes upwards of 200-300Mb (I'm the only person using the application)
- If I remove hard limits, it will consume the entire GCE node's ram before OOM killing, usually around 5Gi available.

**Comment by michaeljguarino** [comment]
Also, if it would help, I can give you access to the code (both client-side and server-side).

**Comment by michaeljguarino** [comment]
Looking around, it might be related to this as well: https://github.com/absinthe-graphql/absinthe/issues/768

**Comment by benwilson512** [comment]
Hey @michaeljguarino, does the OOM happen immediately or does it happen over time? Can you provide the output from `mix deps|grep absinthe` and `mix deps|grep phoenix` ? Are the subscriptions idle or are you also publishing? If publishing can you provide an estimate of publications / second?

**Comment by michaeljguarino** [comment]
It happens pretty much immediately after about 12 subscribe/resubscribes.  I don't even need to publish to OOM it, weirdly enough, although there might be some publishing happening due to background work happening.  But we're talking maybe 2-4 events.

```
➜  piazza git:(master) mix deps | grep absinthe
* absinthe (Hex package) (mix)
  locked at 1.4.16 (absinthe) 0933e4d9
* absinthe_relay (Hex package) (mix)
  locked at 1.4.6 (absinthe_relay) ec0e2288
* absinthe_plug (Hex package) (mix)
  locked at 1.4.7 (absinthe_plug) 939b6b9e
* absinthe_phoenix (Hex package) (mix)
  locked at 1.4.4 (absinthe_phoenix) af3b7b44
➜  piazza git:(master) mix deps | grep absinthe
* absinthe (Hex package) (mix)
  locked at 1.4.16 (absinthe) 0933e4d9
* absinthe_relay (Hex package) (mix)
  locked at 1.4.6 (absinthe_relay) ec0e2288
* absinthe_plug (Hex package) (mix)
  locked at 1.4.7 (absinthe_plug) 939b6b9e
* absinthe_phoenix (Hex package) (mix)
  locked at 1.4.4 (absinthe_phoenix) af3b7b44
➜  piazza git:(master) mix deps | grep phoenix
* phoenix_pubsub (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
* phoenix (Hex package) (mix)
  locked at 1.4.9 (phoenix) 746d098e
* phoenix_live_reload (Hex package) (mix)
  locked at 1.2.1 (phoenix_live_reload) 274a4b07
* phoenix_html (Hex package) (mix)
  locked at 2.13.3 (phoenix_html) 850e292f
* absinthe_phoenix (Hex package) (mix)
  locked at 1.4.4 (absinthe_phoenix) af3b7b44
* phoenix_ecto (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
```

**Comment by benwilson512** [comment]
That is very weird. Can you try the 1.5.0 beta? How large is your schema would you say?

**Comment by michaeljguarino** [comment]
It really shouldn't be that large.  We're talking maybe 10-15 types, with equal numbers of subscription/mutation fields.  Three dataloaders.

Is 1.5.0 beta only on github or can I use hex?  I can try it tonight if you think it might fix it.

**Comment by benwilson512** [comment]
It is definitely on hex. I'll see if I can reproduce on my end as well.

**Comment by michaeljguarino** [comment]
If you want me to send you the repo, I can too.  It's currently private, but it doesn't need to be.

**Comment by benwilson512** [comment]
That would be extremely helpful.

**Comment by michaeljguarino** [comment]
here you go: https://github.com/michaeljguarino/piazza

**Comment by michaeljguarino** [comment]
Ok I just did the 1.5 upgrade and tested and the behavior still remains.

**Comment by michaeljguarino** [comment]
I just configured it to point to master to pull your garbage collection change for the related commit, and the issue has still recurred.  Although a 5 second interval gc sweep isn't even going to be quick enough to catch this.

**Comment by michaeljguarino** [comment]
@benwilson512 So I managed to get on a node that was overconsuming memory, and found this:

```
iex(rtc@10.24.0.250)4> :erlang.memory()
[
  total: 809125960,
  processes: 37056296,
  processes_used: 37053720,
  system: 772069664,
  atom: 1763537,
  atom_used: 1754621,
  binary: 4437160,
  code: 46954910,
  ets: 689206400
]
```

For whatever reason, ets bloated to almost 700Mi.  Is there anything in the code that could cause that?

**Comment by michaeljguarino** [comment]
Digging in a little more, using :ets.i() on a hot node, I found:

```
 #Ref<0.1115617722.2677669890.124533> 'Elixir.RtcWeb.Endpoint.Registry.KeyPartition1' duplicate_bag 10     84769938 'Elixir.RtcWeb.Endpoint.Registry.PIDPartition1'

```

**Comment by benwilson512** [comment]
Can you run:
```
RtcWeb.Endpoint |> Absinthe.Subscription.registry_name |> Registry.count |> div(2)
```
This should give you the number of subscription documents it's holding on to (roughly). The `div(2)` is because each document is minimum two entries, one for the document itself, and another entry with some small metadata.

**Comment by michaeljguarino** [comment]
This is so bizarre:

```
iex(rtc@10.24.0.251)2> :erlang.memory()
[
  total: 806781904,
  processes: 35781528,
  processes_used: 35777984,
  system: 771000376,
  atom: 1763537,
  atom_used: 1754587,
  binary: 3448184,
  code: 46954910,
  ets: 689206776
]
iex(rtc@10.24.0.251)3> RtcWeb.Endpoint |> Absinthe.Subscription.registry_name |> Registry.count |> div(2)
5
```

**Comment by michaeljguarino** [comment]
Ok I dug even deeper and was able to inspect the table without blowing out the node and it looks like a lot of the entries look something like this:
```
{{:participant_delta, "topic_name:...."},
  {pid,
__absinthe__:doc:-576460752303422975:8079521D8F32EA9BFFFE009DCD25E4BD06170F67C7B0B141F5921919BF4A1918",
     %Inspect.Error{
       message: "got FunctionClauseError with message \"no function clause matching in Absinthe.Schema.Notation.SDL.Render.render/1\" while inspecting %{__struct__: Absinthe.Blueprint, adapter: Absinthe.Adapter.LanguageConventions, directives: [], errors: [], execution: %Absinthe.Blueprint.Execution{acc: %{}, adapter: nil, context: %{current_user: %Core.Models.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, avatar: nil, bio: nil, bot: false, deleted_at: nil, email: \"mguarino@fb.com\", handle: \"michael\", id: \"2adcf107-4551-4795-9dd3-5f69af41cb4b\", inserted_at: ~U[2019-07-28 22:06:59.585002Z], jwt: nil, name: \"Michael Guarino\", notification_preferences: nil, password: nil, password_hash: \"$argon2id$v=19$m=131072,t=8,p=4$gXwpdIlcG/Fqm4VspEMPoA$mTqY9uHuwPEYKGAHXHoPShNOHRr0zyn1HxU6y3K2xfw\", profile_img: nil, roles: nil, updated_at: ~U[2019-07-28 22:06:59.585002Z]}, loader: %Dataloader{options: [get_policy: :raise_on_error], sources: %{Core.Resolvers.Conversation => %Dataloader.Ecto{batches: %{}, default_params: %{current_user: %Core.Models.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, avatar: nil, bio: nil, bot: false, deleted_at: nil, email: \"mguarino@fb.com\", handle: \"michael\", id: \"2adcf107-4551-4795-9dd3-5f69af41cb4b\", inserted_at: ~U[2019-07-28 22:06:59.585002Z], jwt: nil, name: \"Michael Guarino\", notification_preferences: nil, password: nil, password_hash: \"$argon2id$v=19$m=131072,t=8,p=4$gXwpdIlcG/Fqm4VspEMPo
```

With that gargantuan binary clogging up most of the space.  I wonder if ets also has its own binary memory leak issue as you sometimes see with non-hibernated processes and the BEAM reports binaries ref-counted by ets as ets space even if freed on a previous delete.  Regardless seems odd that that would be used for the doc

**Comment by michaeljguarino** [comment]
Ok I've found the source of the bug.  I had a function:

```
def context(ctx) do
    loader =
      Dataloader.new()
      |> Dataloader.add_source(Conversation, Conversation.data(ctx))
      |> Dataloader.add_source(User, User.data(ctx))
      |> Dataloader.add_source(Platform, Platform.data(ctx))

    Map.put(ctx, :loader, loader)
  end
```
in my schema, naively assuming it would be executed once at schema-realization time.  Basically, It would shove the current context into the dataloader's default args.  But since it actually seems to be evaluated for each field and accumulated along the way, it would recursively expand as the schema was evaluated, bloating memory far too much.

Fixing that, things are stable, but keeping the parsed documents is still pretty memory inefficient (looks like at least a 50x bigger memory footprint in the case of this app).  This might not be ideal in a stateful subscription context where there could easily be 100000+ documents in flight per node, and paying a few cpu cycles to reparse a relatively tiny gql document isn't that high a price.

**Comment by benwilson512** [comment]
@michaeljguarino the schema level context function is called once per document execution, not once per field. However as you note it is NOT called a compile time, nor could it be since the context includes things like "current user" which is a per request / execution kind of thing.

> This might not be ideal in a stateful subscription context where there could easily be 100000+ documents in flight per node, and paying a few cpu cycles to reparse a relatively tiny gql document isn't that high a price.

Fair, although in some people's case the latency of re-parsing and re-validating the docs over and over may be the larger issue. However, this is definitely something that could be configurable so that users can choose the memory / latency tradeoff that makes the most sense for them.

**Comment by michaeljguarino** [comment]
Hmm that's what I expected then.  The result I was seeing though was basically the dataloader having instances of the dataloader itself in its default args.  I should have copied it and pasted for you to see.  Perhaps I was mistaking how that came about.

Regardless adding a simple key filter on the context for what I actually want (really just the current user) fixed the issue.

**Comment by benwilson512** [comment]
Can you show what you had / have as your subscription setup function?

**Comment by benwilson512** [comment]
I'm also noticing that you reverted the change to 1.5, what issue did you have with it?

**Comment by michaeljguarino** [comment]
I switched because I was suspicious that InspectError in the parsed document was caused by the bump because it referenced the SDL, and I think I was right.

What do you mean by subscription setup function?  All the resolvers should be referenced in `Core.Schema` if you want to poke around.

**Comment by benwilson512** [comment]
@michaeljguarino I've poked around and nothing looks obviously wrong. We can also look at making changes that lower the memory usage of stored docs. I appreciate that you've made the code accessible, are you able to provide directions on how to run it locally such that I can reproduce the problem?

**Comment by michaeljguarino** [comment]
To be honest, I've been doing all the actual e2e development on my personal GKE cluster.  You should be able to helm install it on minikube in theory if absolutely needed. Otherwise, perhaps do:

```
make testsetup
mix phx.server
```

You'll likely need to set up something in GOOGLE_APPLICATION_CREDENTIALS to make the stupid goth client happy though.

**Comment by michaeljguarino** [comment]
If it's easier, I can revert the fix I made just for testing and resynthesize the error.

**Comment by michaeljguarino** [comment]
Actually, I think the best idea if you want to run it yourself is just get it set up for testing, which requires some valid GOOGLE_APPLICATION_CREDENTIALS service account json unfortunately, and just doing `MIX_ENV=test iex -S mix`.  You should be able to execute a graphql doc directly in the repl and traverse the entire structure.  I literally won't be able to copy-paste it in here.

**Comment by benwilson512** [comment]
Right, what I'm looking for is a document that is representative of the kinds of subscriptions you were running that I can use in the REPL, and some code I can run to trigger a publication.

**Comment by michaeljguarino** [comment]
You shouldn't even need to publish to see what was happening.  Just establishing a few subscriptions should start spiking the memory for you.  I'd use:

```
subscription MessageDeltas($conversationId: ID!) {
  messageDelta(conversationId: $conversationId) {
    delta
    payload {
      id
      text
      structuredText
      insertedAt
      creator {
         name
         handle
      }
    }
  }
}
```

(Or just use the full message fragment in `www/src/components/models/conversations.js`

I'm not sure the best way to subscribe in the repl itself but I think I remember there being a way to do it.

If you absolutely do want to generate a publication, create a pubsub event like `%Core.PubSub.MessageCreated{item: msg}` and pass it to `Rtc.Aquaduct.Subscriber.publish_event/1`

**Comment by jwaldrip** [comment]
This is absolutely related to https://github.com/absinthe-graphql/absinthe/issues/768. We have tried to implement garbage collection to remedy this. But there is a clear memory leak that we are unable to resolve. This is OOMing our prod processes at lease once daily. @benwilson512 please help. 🙏

**Comment by michaeljguarino** [comment]
From what I've seen so far it isn't a memory leak per se, but rather the parsed representation of the document stored in ets being extremely heavy and thus causing an OOM.  I was able to stabilize it by trimming what I passed to my dataloaders, but it's possible there are other issues.

**Comment by benwilson512** [comment]
@jwaldrip I am working to reproduce this with @michaeljguarino's code, and I expect to have a fix out in 1.5 today that will switch the storage of documents to use the original query string instead of the blueprint. This should help if your OOM issue is related simply to the number of stored documents.

**Comment by cjbell** [comment]
Had the same issue that @michaeljguarino described here in absinthe `1.5.2` (sidenote: 👋 hi michael!). Was seeing memory go from 70mb → 8gb in a couple of subscribes and unsubscribe loops from my client.

I checked my data loading builder code and I was also passing the full context object down to my dataloader for the purposes of having the current user present in the dataloader args.

Fix for me was to simply add `context = Map.take(context, [:current_user])` so that I only pass an allowed list of keys through the context. After that memory use has stabilized for and no more OOM errors 🎉

**Comment by michaeljguarino** [comment]
Yeah that's the exact same fix I used as well.

**Comment by benwilson512** [comment]
Great glad to hear it!
