### ISSUE TITLE
CRUD Generators (Schema + Resolvers + Tests)

### ISSUE THREAD

**Issue by popo63301** [absinthe-graphql/absinthe_phoenix#69]
Hello !

I'm wondering why there isn't any generators available for this library since it's been available for a moment. Is it something you've ever considered to do ? Because it would be awesome to have generators to speed up the work process with Absinthe ! 

Thanks

**Comment by benwilson512** [comment]
Hi @popo63301. The issue tracker isn't really for feature requests. The project lacks generators because unfortunately I don't have any time to write and maintain generators.
