### ISSUE TITLE
Bump decimal dependency to 2.0

### ISSUE THREAD

**Issue by ckruse** [absinthe-graphql/absinthe_phoenix#75]
Jason needs `~> 1.0` or `~> 2.0`, postgrex needs `~> 1.5` or `~> 2.0` and absinthe_phoenix requires `~> 1.0` – that's a conflict :-)

**Comment by suhanlee** [comment]
@ckruse If you try to remove `mix.lock` and do execute `mix deps.get`. It will find specific version(1.0~2.0, In my case, 1.9.0)

**Comment by benwilson512** [comment]
This was only included in one of the more recent releases.

**Comment by tcitworld** [comment]
Why not set it to `~> 1.0 or ~> 2.0` like in absinthe though?

**Comment by zdcthomas** [comment]
I wanna bump this thread, is there a specific reason to not require `~> 1.0` or `~> 2.0`?
