### ISSUE TITLE
Support for request context data.

### ISSUE THREAD

**Issue by vic** [absinthe-graphql/absinthe_phoenix#8]
Hello, this is more a question than an proper issue I guess.

I'm about to update an application of mine to use absinthe subscriptions branch and absinthe_phoenix socket, however, I'm not sure on how to implement the following:

Using the Apollo client, you can specify [middle-wares that can intercept any request](http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware) before it's
being sent. AFAIK it's mainly used for cases like [authorization](http://dev.apollodata.com/react/auth.html#Header) where every request is also sent with the current authentication token from the client. 

So for example, the Apollo client on my app is configured to always send not only the gql document, and its variables, but also two additional things: the authentication token stored on the device, and the local-time of such device at the moment the query was made (most of the backend operations are sensitive to the user's local time). 

So previously to `absinthe_phoenix` my dumb Channel received "docs" something like this
example

```elixir
  def handle_in("doc", request = %{"query" => query}, socket) when do
     variables = Map.get(request, "variables", %{})
     context = request_context(%{}, request)

     options = [variables: variables, context: context]

     # Unlike Absinthe.Phoenix.Channel, my version just relied on Absinthe.run
     # as it was the simplest way I found to execute the query.
     # then, the resolve function could have access to the jwt token and localtime
     # stored in the context map.
     #
     # IIRC this was how I was executing queries on my tests also.
     {:ok, result} = Absinthe.run(query, MyGQL.Schema, options)

     {:reply, {:ok, result}, socket}
   end

   defp request_context(context, request) do
      context
      |> authentication_context(request)
      |> device_localtime_context(request)
   end

   defp authentication_context(context, %{"auth_token" => token}) do
      Map.put(context, :jwt, token)
   end
   defp authentication_context(context, _), do: context
 
   defp device_localtime_context(context, %{"time" => time_str}) do
      Map.put(context, :local_time, Time.parse_iso!(time_str))
   end
   defp device_localtime_context(context, _), do: context

```

```elixir
  def resolve_function(_parent, variables, %{context: context}) do
    # the resolve functions have access to the jwt token and the client device time.
  end
```

So, now I'm wondering how I should send these "context" data so that the absinthe_phoenix's Channel can send it to my resolve functions. Any idea on how to approach this is more than welcome :)

**Comment by G3z** [comment]
i think this issue is solved as absinthe_phoenix handles the context for channels

**Comment by benwilson512** [comment]
Hey @vic. You can set the context for the channel in the `def connect` callback of your socket module, and it can be updated by mutations as necessary.
