### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dolfinus** [absinthe-graphql/absinthe_phoenix#82]
Hi.

What do you think about releasing new version of absinthe_phoenix? The last one was released on May 2020, and a bunch of new bugfixes/features has ben added into the master branch since when.

**Comment by doughsay** [comment]
I especially would like the addition of Decimal 2.0 support, as well as not requiring `override: true` to use Absinthe 1.6 😄

**Comment by dolfinus** [comment]
@benwilson512 Could you please take a look at this?

**Comment by benwilson512** [comment]
v2.0.1 has been published, thanks for your patience.
